front/Presentation/Controllers/AuthorizationController.cs
using Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Controllers;


public class AuthorizationController : Controller
{
    private readonly SignInManager<User> _signInManager;
    private readonly UserManager<User> _userManager;

    public AuthorizationController(SignInManager<User> signInManager, UserManager<User> userManager)
    {
        _signInManager = signInManager;
        _userManager = userManager;
    }

    [HttpGet]
    public IActionResult Authorization() => View();

    [HttpGet]
    public IActionResult SingUp() => View();
    [HttpPost]
    public async Task<IActionResult> SingUp(string email, string password)
    {
        var user = await _userManager.FindByEmailAsync(email);
        if (user != null)
        {
            var result = await _signInManager.PasswordSignInAsync(user, password, false, false);
            if (result.Succeeded)
                return RedirectToAction("Index", "Home");
        }
        ModelState.AddModelError("", "Неверные данные");
        return View();
    }

    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Login");
    }

    public IActionResult AccessDenied() => View();
}

front/Presentation/Views/Authorization/Authorization.cshtml
Authorization.html:@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name = "viewport" content = "width=device-width">
    <link rel = "stylesheet" href = "css/Authorization.css">
    <title>Регистрация</title>
</head>

<body class = "zero_margin">
<div class = "Layer">
    <div class = "auth_background zero_margin">
        <p class = "company base">Take Fusion</p>
        <p class = "company_title base font_hezaedrus">Начни прямо сейчас</p>
        <p class = "company_description base font_hezaedrus">Выполни простые действия для начала работы</p>
        <div class = "steps-container">
            <div class = "step first-step">
                <div class = "counter-steps first-steps-color">
                    <p class = "counter-steps_first font_hezaedrus">1</p>
                </div>
                <p class = "first-descript-color step-margin font_hezaedrus">Зарегистрируйся</p>
            </div>
            <div class = "step">
                <div class = "counter-steps base_steps-color">
                    <p class = "counter-steps_second font_hezaedrus">2</p>
                </div>
                <p class = "step-descript step-margin font_hezaedrus">Выбери телефонию</p>
            </div>
            <div class = "step">
                <div class = "counter-steps base_steps-color">
                    <p class = "counter-steps_second font_hezaedrus">3</p>
                </div>
                <p class = "step-descript step-margin font_hezaedrus">Введи уникальный токен и начинай</p>
            </div>
        </div>
    </div>

    <div class = "auth_model zero_margin">
        <div class="auth-button-container">
            <a class="auth-button font_hezaedrus" href="@Url.Action("SingUp", "Authorization")">Войти</a>
        </div>
        <div class = "auth_model-container">
            <p class = "auth-title font_hezaedrus">Регистрация аккаунта</p>
            <div class = "auth-label">
                <p class ="auth-p font_hezaedrus">Логин</p>
                <div class = "auth-form">
                    <label class = "login-input">
                        <input id="login" type="text" maxlength="25"/>
                    </label>
                </div>
            </div>
            <div class = "auth-label">
                <p class ="auth-p font_hezaedrus">Email</p>
                <div class = "auth-form">
                    <label class = "email-input">
                        <input id="email" type="email"/>
                    </label>
                </div>
            </div>
            <div class = "auth-label">
                <p class ="auth-p font_hezaedrus">Пароль</p>
                <div class = "auth-form">
                    <label class = "password-input">
                        <input id="password" type="password" maxlength="50"/>
                    </label>
                </div>
            </div>
            <a class = "register-button font_hezaedrus" href="#">
                Регистрация
            </a>
        </div>
    </div>
</div>
</body>

</html>

front/Presentation/Views/Authorization/SingUp.cshtml
SingUp.html:
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name = "viewport" content = "width=device-width">
    <link rel="stylesheet" href="~/css/Authorization.css">
    <title>Вход</title>
</head>

<body class = "zero_margin">
<div class = "Layer">
    <div class = "auth_background zero_margin">
        <p class = "company base">Take Fusion</p>
        <p class = "company_title base font_hezaedrus">Начни прямо сейчас</p>
        <p class = "company_description base font_hezaedrus">Выполни простые действия для начала работы</p>
        <div class = "steps-container">
            <div class = "step first-step">
                <div class = "counter-steps first-steps-color">
                    <p class = "counter-steps_first font_hezaedrus">1</p>
                </div>
                <p class = "first-descript-color step-margin font_hezaedrus">Зарегистрируйся</p>
            </div>
            <div class = "step">
                <div class = "counter-steps base_steps-color">
                    <p class = "counter-steps_second font_hezaedrus">2</p>
                </div>
                <p class = "step-descript step-margin font_hezaedrus">Выбери телефонию</p>
            </div>
            <div class = "step">
                <div class = "counter-steps base_steps-color">
                    <p class = "counter-steps_second font_hezaedrus">3</p>
                </div>
                <p class = "step-descript step-margin font_hezaedrus">Введи уникальный токен и начинай</p>
            </div>
        </div>
    </div>

    <div class = "auth_model zero_margin">
        <div class="reg-button-container">
            <a class="reg-button font_hezaedrus" href="@Url.Action("Authorization", "Authorization")">Регистрация</a>
        </div>
        <div class = "join_model-container">
            <p class = "auth-title font_hezaedrus">Вход</p>
            <div class = "auth-label">
                <p class ="auth-p font_hezaedrus">Логин</p>
                <div class = "auth-form">
                    <label class = "login-input">
                        <input id="login" type="text" maxlength="25"/>
                    </label>
                </div>
            </div>
            <div class = "auth-label">
                <p class ="auth-p font_hezaedrus">Пароль</p>
                <div class = "auth-form">
                    <label class = "password-input">
                        <input id="password" type="password" maxlength="50"/>
                    </label>
                </div>
            </div>
            <a class = "register-button font_hezaedrus" href="#">
                Войти
            </a>
        </div>
    </div>
</div>
</body>
<html/>

front/Presentation/Views/Home/SingUp.cshtml
hui